[workspace]
members = [
    "google-androidpublisher-rest",
    "google-androidpublisher-rest/demo",
    "google-cloud-vision-rest",
    "google-cloud-vision-rest/demo",
    "google-rest-resource-method",
]
