[package]
name = "google-androidpublisher-rest"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
google-rest-resource-method = { path = "../google-rest-resource-method", version = "0.1", default-features = false, features = [] }
