[package]
name = "google-rest-endpoint"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
http = { version = "0.2", default-features = false, features = [] }
